# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: amazing_amazon_sept
  username: postgres
  password: pg123

test:
  <<: *default
  # database: db/test.sqlite3

production:
  <<: *default
  # database: db/production.sqlite3
